[pytest]
markers =
    browser: tests E2E Playwright (navigateur)
filterwarnings =
    ignore:datetime\.datetime\.utcnow\(\) is deprecated:DeprecationWarning
    ignore:on_event is deprecated:DeprecationWarning
    ignore:Please use `import python_multipart`:PendingDeprecationWarning
